### ISSUE TITLE
Error with docker image elasticsearch-dendro

### ISSUE THREAD

**Issue by mdehollander** [feup-infolab/dendro-install-docker#1]
I am giving the docker-compose installation a quick try and ran into this error:

```
elasticsearch-dendro | [2018-10-03T18:40:09,068][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch-dendro | [2018-10-03T18:40:09,093][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch-dendro | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch-dendro | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch-dendro | 	at org.elasticsearch.node.Node.<init>(Node.java:267) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	... 6 more
elasticsearch-dendro | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch-dendro | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
elasticsearch-dendro | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
elasticsearch-dendro | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
elasticsearch-dendro | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
elasticsearch-dendro | 	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_161]
elasticsearch-dendro | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_161]
elasticsearch-dendro | 	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_161]
elasticsearch-dendro | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:204) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.node.Node.<init>(Node.java:264) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.2.jar:6.2.2]
elasticsearch-dendro | 	... 6 more
virtuoso-dendro  | 18:40:09 HTTP/WebDAV server online at 8890
virtuoso-dendro  | 18:40:09 Server online at 1111 (pid 1)
elasticsearch-dendro exited with code 1
```

I am using Ubuntu 16.04 LTS, docker-compose version 1.22.0 and Docker version 17.09.1-ce

**Comment by silvae86** [comment]
Hello!

I will take a look at it in the next days and get back to you.

Thanks!

**Comment by mdehollander** [comment]
I think it is related to https://github.com/elastic/elasticsearch-docker/issues/21

As a test I set the permission of the ./volumes/elasticsearch to 777. Then it works. So it has something to do with permissions or user/group. But the correct fix I don know.
